server:
  port: 8888
  
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 #최적화 옵션
        
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true